/*
 * This source file was generated by the Gradle 'init' task
 */
import com.google.inject.Guice;
import com.google.inject.Injector;

import interfaces.IBusiness;


/**
 * The App class serves as the entry point for the application.
 * It creates an instance of the Business class and calls its doBusiness method.
 * The result of the doBusiness method is printed to the console twice.
 */
public class App {


    /**
     * The main method serves as the entry point for the application.
     * It creates an instance of the Business class, calls its doBusiness method,
     * and prints the result to the standard output.
     *
     * @param args Command-line arguments passed to the application.
     */
    public static void main(String[] args) {

        Injector injector = Guice.createInjector(new BusinessModule());
        IBusiness business = injector.getInstance(IBusiness.class);
        
        String result = business.doBusiness();

        System.out.println(result);

        System.exit(0);
    }
}
