/*
 * This source file was generated by the Gradle 'init' task
 */


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;


class AppTest {

    @Test
    void testMain() {
        // Set up the output stream to capture the output
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        // Call the main method
        App.main(new String[]{});

        // Reset the standard output
        System.setOut(System.out);
    }
}
